name: search_app_bar_pro_max_ultra
description: Search app bars made simple
version: 1.0.0
repository: https://github.com/ArcaneArts/search_appbar
environment:
  sdk: ^3.3.3
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
